import { useEffect, useState } from 'react'
import { AlertCircle, CheckCircle2, Send, X } from 'lucide-react'
import { listSubmittableReadings, submitRecommendationForReview } from '../services/supabase/recommendationService'

const fieldStyle = { width: '100%', padding: '10px 12px', borderRadius: 10, border: '1px solid var(--surface-border)', background: 'var(--card-bg-warm)', color: 'var(--ink)', fontFamily: 'DM Sans', fontSize: 13 }
const labelStyle = { display: 'block', marginBottom: 6, fontFamily: 'DM Sans', fontSize: 12, fontWeight: 600, color: 'var(--ink)' }
const noteStyle = { fontFamily: 'DM Sans', fontSize: 12, color: 'var(--ink-muted)', lineHeight: 1.65 }

export default function SubmitRecommendationModal({ onClose, onSubmitted, preSelectedId = null }) {
  const [items, setItems] = useState([]); const [selectedId, setSelectedId] = useState('')
  const [title, setTitle] = useState(''); const [author, setAuthor] = useState(''); const [sourceUrl, setSourceUrl] = useState('')
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(false)
  useEffect(() => { let active = true; listSubmittableReadings().then(d => { if (active) { setItems(d); if (preSelectedId && d.some(item => item.id === preSelectedId)) setSelectedId(preSelectedId) } }).catch(e => { if (active) setError(e.message || '无法加载可提交内容') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [preSelectedId])
  useEffect(() => { const item = items.find(x => x.id === selectedId); setTitle(item?.title || ''); setAuthor(item?.author || ''); setSourceUrl(item?.source_url || ''); setError('') }, [selectedId, items])
  useEffect(() => { const key = e => { if (e.key === 'Escape' && !submitting) onClose() }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [onClose, submitting])
  async function submit() { if (!selectedId || !title.trim()) return; setSubmitting(true); setError(''); try { await submitRecommendationForReview({ readingId: selectedId, title: title.trim(), author: author.trim(), sourceUrl: sourceUrl.trim() }); setSuccess(true) } catch (e) { setError(e.message || '提交失败，请稍后再试') } finally { setSubmitting(false) } }
  const button = { padding: '9px 16px', borderRadius: 10, fontFamily: 'DM Sans', fontSize: 13, cursor: 'pointer' }
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 overflow-y-auto" style={{ background: 'rgba(0,0,0,.38)', backdropFilter: 'blur(3px)', overscrollBehavior: 'contain' }} onClick={e => { if (e.target === e.currentTarget && !submitting) onClose() }}>
    <section role="dialog" aria-modal="true" aria-labelledby="recommendation-submit-title" className="w-full rounded-3xl p-6 sm:p-8" style={{ maxWidth: 520, background: 'var(--popup-bg)', boxShadow: 'var(--popup-shadow)' }}>
      {success ? <div className="flex flex-col items-center text-center py-8"><CheckCircle2 size={32} style={{ color: '#16a34a', marginBottom: 14 }} /><h2 id="recommendation-submit-title" style={{ fontFamily: 'DM Sans', fontSize: 18, fontWeight: 700, color: 'var(--ink)' }}>已提交审核</h2><p style={{ ...noteStyle, marginTop: 8 }}>管理员完成审核后，你可以在“我的推荐”查看状态。</p><button onClick={onSubmitted} style={{ ...button, marginTop: 24, border: 'none', background: 'var(--ink)', color: 'var(--on-ink)', fontWeight: 600 }}>完成</button></div> : <>
        <div className="flex items-start justify-between gap-4 mb-6"><div><h2 id="recommendation-submit-title" style={{ fontFamily: 'DM Sans', fontSize: 18, fontWeight: 700, color: 'var(--ink)' }}>提交推荐审核</h2><p style={{ ...noteStyle, marginTop: 5 }}>提交后由管理员审核、编辑并决定是否发布。</p></div><button onClick={onClose} disabled={submitting} aria-label="关闭提交推荐窗口" style={{ border: 'none', background: 'transparent', color: 'var(--ink-muted)', cursor: 'pointer', padding: 4 }}><X size={18} aria-hidden="true" /></button></div>
        {loading ? <p aria-live="polite" style={noteStyle}>正在加载可提交内容…</p> : items.length === 0 ? <div className="rounded-2xl p-5 text-center" style={{ background: 'var(--parchment-50)', border: '1px solid var(--border-subtle)' }}><AlertCircle size={22} style={{ color: 'var(--ink-muted)', opacity: .5, marginBottom: 8 }} /><p style={noteStyle}>暂无可提交内容。只有已读完的自导入内容可以提交，并且同一内容只能提交一次。</p></div> : <div className="flex flex-col gap-4"><div><label htmlFor="recommendation-reading" style={labelStyle}>选择已读完的内容</label><select id="recommendation-reading" value={selectedId} onChange={e => setSelectedId(e.target.value)} style={fieldStyle}><option value="">请选择…</option>{items.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div>
          {selectedId && <><div><label htmlFor="recommendation-title" style={labelStyle}>标题</label><input id="recommendation-title" value={title} onChange={e => setTitle(e.target.value)} style={fieldStyle} /></div><div><label htmlFor="recommendation-author" style={labelStyle}>作者</label><input id="recommendation-author" value={author} onChange={e => setAuthor(e.target.value)} placeholder="可选" style={fieldStyle} /></div><div><label htmlFor="recommendation-url" style={labelStyle}>来源链接</label><input id="recommendation-url" type="url" value={sourceUrl} onChange={e => setSourceUrl(e.target.value)} placeholder="可选，例如：https://example.com/article" style={fieldStyle} /></div></>}
          <p style={{ ...noteStyle, padding: '12px 14px', borderRadius: 12, background: 'var(--parchment-50)' }}>提交后不可撤回；若未通过审核，不能再次提交同一内容。</p>{error && <p role="alert" style={{ ...noteStyle, color: 'var(--danger-text)' }}>{error}</p>}<div className="flex justify-end gap-3" style={{ borderTop: '1px solid var(--popup-divider)', paddingTop: 16 }}><button onClick={onClose} disabled={submitting} style={{ ...button, border: '1px solid var(--surface-border)', background: 'transparent', color: 'var(--ink-muted)' }}>取消</button><button onClick={submit} disabled={!selectedId || !title.trim() || submitting} className="flex items-center gap-2" style={{ ...button, border: 'none', background: 'var(--ink)', color: 'var(--on-ink)', fontWeight: 600, opacity: (!selectedId || !title.trim() || submitting) ? .45 : 1 }}><Send size={14} aria-hidden="true" />{submitting ? '提交中…' : '提交审核'}</button></div></div>}
      </>}
    </section>
  </div>
}
